# Sample training configuration for SWIN Mask R-CNN

# Dataset paths
train_ann: /home/georgepearse/data/cmr/annotations/2025-05-15_12:38:23.077836_train_ordered.json
val_ann: /home/georgepearse/data/cmr/annotations/2025-05-15_12:38:38.270134_val_ordered.json
img_root: /home/georgepearse/data/images

# Model parameters
num_classes: 69
rpn_cls_pos_weight: 5.0  # Increase to emphasize positive samples
rpn_loss_cls_weight: 1.0
rpn_loss_bbox_weight: 1.0
roi_cls_pos_weight: 3.0  # Increase for foreground emphasis
roi_loss_cls_weight: 1.0
roi_loss_bbox_weight: 1.0
roi_loss_mask_weight: 1.0

# Training parameters
train_batch_size: 2
val_batch_size: 4
num_workers: 7
lr: 0.0001
momentum: 0.9
weight_decay: 0.05
num_epochs: 12

# Iteration-based validation
steps_per_validation: 200
validation_start_step: 200  # Start validation at the same step as steps_per_validation

# Gradient clipping
clip_grad_norm: 10.0

# Checkpointing and logging
checkpoint_dir: ./test_checkpoints
log_interval: 50
save_interval: null  # null for epoch-based saving

# Optimizer choice
optimizer: adamw  # or 'sgd'

# Learning rate scheduler
use_scheduler: true

# Mixed precision training
use_amp: false

# Model settings
pretrained_backbone: true
pretrained_checkpoint_url: https://download.openmmlab.com/mmdetection/v2.0/swin/mask_rcnn_swin-s-p4-w7_fpn_fp16_ms-crop-3x_coco/mask_rcnn_swin-s-p4-w7_fpn_fp16_ms-crop-3x_coco_20210903_104808-b92c91f1.pth
frozen_backbone_stages: 2  # Number of SWIN backbone stages to freeze (-1 for none, 0-4 to freeze stages)

# Validation settings
validation_iou_thresh: 0.5
max_val_images: 50  # Limit validation to 50 images for faster debugging
