# Quick test config to verify detection fix
# Based on config.yaml with shorter training

# Dataset paths
train_ann: /home/georgepearse/data/cmr/annotations/2025-05-15_12:38:23.077836_train_ordered.json
val_ann: /home/georgepearse/data/cmr/annotations/2025-05-15_12:38:38.270134_val_ordered.json
img_root: /home/georgepearse/data/images

# Model parameters
num_classes: 69

# Training parameters
train_batch_size: 2
val_batch_size: 2
num_workers: 4
lr: 0.0001
momentum: 0.9
weight_decay: 0.05
num_epochs: 1

# Quick validation
steps_per_validation: 50
validation_start_step: 50

# Gradient clipping
clip_grad_norm: 10.0

# Checkpointing and logging
checkpoint_dir: ./test_checkpoints/detection_fix_test
log_interval: 10
save_interval: null

# Optimizer choice
optimizer: adamw

# Learning rate scheduler
use_scheduler: true

# Mixed precision training
use_amp: false

# Model settings
pretrained_backbone: true
pretrained_checkpoint_url: https://download.openmmlab.com/mmdetection/v2.0/swin/mask_rcnn_swin-s-p4-w7_fpn_fp16_ms-crop-3x_coco/mask_rcnn_swin-s-p4-w7_fpn_fp16_ms-crop-3x_coco_20210903_104808-b92c91f1.pth
frozen_backbone_stages: 2

# Validation settings
validation_iou_thresh: 0.5
max_val_images: 10  # Very small for quick test