name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=swin_maskrcnn --cov-report=xml
    
    - name: Run type checking
      run: |
        mypy swin_maskrcnn/
    
    - name: Run linter
      run: |
        ruff check .
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true